name: Build Executable

on: 
  push:  # Triggers on all branch pushes
  pull_request:  # Triggers on pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build Executable
        run: |
          nuitka --standalone --show-progress --plugin-enable=qt-plugins main.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3  # Ensure you're using the latest version
        with:
          name: liventcord-executable
          path: ./main.dist/
