name: Build Executable

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build Executable
        run: |
          echo "Building the executable..."
          nuitka --standalone --show-progress \
                 --plugin-enable=qt-plugins \
                 --include-qt-plugins=all \
                 --include-qt-plugins=sensible,styles \
                 main.py

      - name: List files in build directory
        run: ls -la ./main.dist/

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: liventcord-executable
          path: ./main.dist/*
